kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "homer.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}