---
# Source: homer/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
  labels:
    {{- include "homer.labels" . | nindent 4 }}
data:
  config.yml: |-
    {{- .Values.configmap.config | nindent 4 }}